### ISSUE TITLE
Port recent geojson-vt improvements and bugfixes

### ISSUE THREAD

**Issue by mourner** [mapbox/geojson-vt-cpp#11]
- [x] fix a silly bug with getTile generating unnecessary tiles https://github.com/mapbox/geojson-vt/commit/53ecc21c978314b166c054ce6a17f3d548cc92dc
- [x] depth-first tiling https://github.com/mapbox/geojson-vt/commit/ec70671d5f96dbae3ad980b1b21d686a50d2125c
- [x] fix broken clipped square heuristics https://github.com/mapbox/geojson-vt/commit/0d16d1938d4d611854c3c22ab78686049a970c77 and https://github.com/mapbox/geojson-vt/commit/cf21ce94902b264ba41d5da1dab100fe7fbdcc91
- [x] return null on invalid/non-existing tiles https://github.com/mapbox/geojson-vt/commit/27aea1cf4880549bf83338c9f85697fe82fb4e2b
- [x] don't generate tiles on empty GeoJSON https://github.com/mapbox/geojson-vt/commit/7cfb6391a8e695ebd4b17c08fd42c90bf897dd82
- [x] make sure test coverage is up to date

cc @incanus @kkaefer

**Comment by mourner** [comment]
@incanus @kkaefer at least the first one should be ported and integrated into GL ASAP because it's a serious bug.

**Comment by incanus** [comment]
> at least the first one should be ported and integrated into GL ASAP because it's a serious bug.

Flagging here that per https://github.com/mapbox/mapbox-gl-native/issues/2226 we have a lot of changes that are also still not in GL — 40 commits and 97 changed files currently.

**Comment by kkaefer** [comment]
I ported all applicable commits in the order they appeared in JS and it's passing with all of the updated tests.
