### ISSUE TITLE
shapes across date line still don't tile properly

### ISSUE THREAD

**Issue by incanus** [mapbox/geojson-vt-cpp#16]

**Comment by ljbade** [comment]
There should be a test case for this.

**Comment by mourner** [comment]
Is this reproducible after the GeoJSON-VT update? (https://github.com/mapbox/mapbox-gl-native/pull/2584)

**Comment by mourner** [comment]
Just made this test case in geojson.io like this:

![image](https://cloud.githubusercontent.com/assets/25395/11673708/ddf914f6-9dcf-11e5-8404-0295fa3db56d.png)

Looking good in GeoJSON-VT:

![image](https://cloud.githubusercontent.com/assets/25395/11673721/eab2e276-9dcf-11e5-9854-0e7200a999df.png)
