### ISSUE TITLE
Port fixes from JS geojson-vt

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/geojson-vt-cpp#17]
- [ ] https://github.com/mapbox/geojson-vt/issues/46 (https://github.com/mapbox/geojson-vt/commit/51a0a7d8ef488bc7f375bf308abaa316c68691b6)
- [x] https://github.com/mapbox/geojson-vt/commit/320863b739a1893eafe6fabc63eb948c5acb41e1 (to mirror the code structure)
- [x] https://github.com/mapbox/geojson-vt/commit/742ec68dc5daeab9f9fab4978cab0d424fd688a1

**Comment by mourner** [comment]
Also worth porting:

- https://github.com/mapbox/geojson-vt/commit/320863b739a1893eafe6fabc63eb948c5acb41e1 (to mirror the code structure)
- https://github.com/mapbox/geojson-vt/commit/742ec68dc5daeab9f9fab4978cab0d424fd688a1
