### ISSUE TITLE
remove geojsonvt_ from include file names

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/geojson-vt-cpp#23]
The includes are already in a `geojsonvt` subdirectory, so prefixing the file names is unnecessary redundancy. Including should instead look like:

```
#include <mapbox/geojsonvt/types.hpp>
```

Or, for the omnibus:

```
#include <mapbox/geojsonvt.hpp>
```

**Comment by mourner** [comment]
This is the same as #7 right?

**Comment by jfirebaugh** [comment]
Basically. I didn't consider the source files, but yeah, we should do the same with them.
