### ISSUE TITLE
Recreate (partial) geometry from tiles

### ISSUE THREAD

**Issue by benstadin** [mapbox/geojson-vt-cpp#29]
I wonder how it's possible to generate a (partial) single geometry which has been sliced. So say, I have a geometry spanning over 6 tiles in total, for of these tiles are within the visible area: How can I create a single geometry (WKT / WKB) from the visible tiles?

Cheers
Ben

**Comment by mourner** [comment]
This is something that we want to look at eventually but is out of scope for geojson-vt. We need to find an efficient algorithm for doing a boolean union of shapes clipped by axis-aligned boxes. You could try doing this manually with a generic clipper by finding all features with the same id within all loaded tiles, although this would be slow.

**Comment by benstadin** [comment]
Maybe this is not required, when additional info can be stored at the time the geometry gets tiled? 

Roughly something like:
- When creating the tiles, remember the (local) point index(indices) within a point set (line string, linear rings, ..) before leaving the tile bounds. 
- Store these point indices as additional "stitch" info for each geometry, for all sides (left, top, bottom, right) of a vector tile. So e.g. when geometry A in tile x leaves the tile bounds to a tile above between tile-local point set index 2-3 and to the right at tile-local point set index 20-21, store point index 2 as the stitch info for "top", and point index 20 as stitch info "right" for this tile.
- When reassembling the tiles, recreate the "whole partial" geometry by copying whole ranges of points up to these stitch points in two phases: (1) Put geometry info for all loaded tiles into a hash table, where each geometry has multiple entries (linked list in hash table buckets for duplicate entries).

**Comment by benstadin** [comment]
I hope this doesn't make you laugh, maybe it's a stupid idea also. I'm not yet into the details of how the tiling algorithm works. 

Anyways, what about this idea:
- For each geometry within a tile, store an array the size of number of geometry points. 
- This array relates local point array indices of the tiled geometry to point indices of the original complete geometry. For a first simplified example, let's say we have a line string with 4 points and two points are in tile a, two points in tile b. We store [0, 1] as relationship info for tile a for this geometry, and [2, 3] in tile b. 
- Now the above example was simplified to express the idea. For points that have been introduced when the geometry was tiled, we use a negative value to mark that this is a tile-point. E.g. for tile a we'd in our example store [0, -1] when point at index 0 is within tile a, and point at index 1 is outside. 
- The geometry could then be prepared together by allocating an array the size of all available points for that geometry (the maximum required size)
- To stitch the tile back into one piece we just loop all tiles, we lookup the above prepared "whole partial" geometry points set.
- We loop over the array->local point index array, use the local array index to get the local point coordinate, and take the absolute value (-1 -> 1) to store e.g. the point coordinates for a tile-algorithm-introduced point at index 1 in the whole-geometry struct
- The trick here is the use of negative values to mark tile-algorithm introduced points. When copying coordinates to the whole-geom struct, a positive index value takes precedence over negative (tile-algorithm introduced) points and overwrite these

There is no hash algorithm required that way, just quick array access. Maybe this can be done efficiently.

There are certainly things I didn't consider. However, is this a stupid idea? Or is it worth to continue with? We'd be willing to contribute implementation of this.

Some quickly drawn example, at the top showing a geometry that can be put together entirely, having created a point index 0-5 for the recreated geometry. On bottom: The top-left tile (a) of the same geometry, with introduced points along the bottom and right side of the tile. These introduced points along the borders have the same absolute index into the array of the original geometry's point set nut negated to mark their introduction due to tiling. 

![img_6705 jpg](https://cloud.githubusercontent.com/assets/1433419/11851252/feedb47e-a431-11e5-96b5-f09b1d39d6b2.jpeg)

**Comment by mourner** [comment]
@benstadin I'll look into the idea closer when I get the chance, but I just remembered that @peterqliu is also very insterested in solving this so may have some further comments. I closed the issue here just because it's not relevant for geojson-vt, while the task is still interesting and potentially important.
