### ISSUE TITLE
configure: confusion about pyhton version.

### ISSUE THREAD

**Issue by 5chdn** [mapbox/geojson-vt-cpp#30]
I can not configure geojson-vt-cpp, due to:

    0 ✓ user@x230 ~/some/path/geojson-vt-cpp $ ./configure 
    Submodule '.mason' (https://github.com/mapbox/mason.git) registered for path '.mason'
    Cloning into '.mason'...
    remote: Counting objects: 3447, done.
    remote: Compressing objects: 100% (3/3), done.
    remote: Total 3447 (delta 0), reused 0 (delta 0), pack-reused 3444
    Receiving objects: 100% (3447/3447), 1.31 MiB | 860.00 KiB/s, done.
    Resolving deltas: 100% (1142/1142), done.
    Checking connectivity... done.
    Submodule path '.mason': checked out '6b1f381d9cdfdf98586961c122722bc6f803ce57'
    * Loading install script 'https://github.com/mapbox/mason/blob/rapidjson-1.0.2/script.sh'...
    * Downloading binary package headers/rapidjson/1.0.2.tar.gz...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 68766  100 68766    0     0  58866      0  0:00:01  0:00:01 --:--:-- 58875
    * Installed binary package at /home/user/some/path/geojson-vt-cpp/mason_packages/headers/rapidjson/1.0.2
      File "<string>", line 1
        import sys, re; print filter(None, re.split('(?<!-framework)\s+', ' '.join(sys.argv[1:])))
                                   ^
    SyntaxError: invalid syntax

The issue is with line 26:

https://github.com/mapbox/geojson-vt-cpp/blob/master/configure#L26

python refers to python 3.5 but this line is clearly asking for python 2.7:

    0 ✓ user@x230 ~/some/path/geojson-vt-cpp $ python --version
    Python 3.5.1
    0 ✓ user@x230 ~/some/path/geojson-vt-cpp $ python2 --version
    Python 2.7.11

Not sure whether this is OS specific, on Archlinux python command always points to python 3.

**Comment by 5chdn** [comment]
Same in the compiling step.

    0 ✓ user@x230 ~/some/path/geojson-vt-cpp $ make -j4
    deps/run_gyp geojsonvt.gyp -Iconfig.gypi --depth=. -Goutput_dir=. --generator-output=./build -f make
    Traceback (most recent call last):
      File "deps/run_gyp", line 5, in <module>
        import gyp
      File "deps/gyp/pylib/gyp/__init__.py", line 37
        print '%s:%s:%d:%s %s' % (mode.upper(), os.path.basename(ctx[0]),
                             ^
    SyntaxError: invalid syntax
    Makefile:22: recipe for target 'lib' failed
    make: *** [lib] Error 1


https://github.com/mapbox/geojson-vt-cpp/blob/master/deps/run_gyp#L1

Should it be `#!/usr/bin/env python2` ?

**Comment by jfirebaugh** [comment]
This is a problem for distributions which don't follow the [PEP 0394](https://www.python.org/dev/peps/pep-0394/) recommendation of keeping `python` aliased to `python2` rather than `python3`. The issue is compounded by Mac OS X _also_ not following PEP 0394 and providing a `python2` alias, which means we can't simply switch the shebangs to `python2` without breaking things for OS X developers.

**Comment by 5chdn** [comment]
ok, thanks for the link to the pep 394.
