### ISSUE TITLE
Converting from geometry.hpp to internal representation

### ISSUE THREAD

**Issue by mourner** [mapbox/geojson-vt-cpp#40]
Currently, [convert.cpp](https://github.com/mapbox/geojson-vt-cpp/blob/master/src/convert.cpp) code converts from GeoJSON data in RapidJSON representation to GeoJSON-VT internal representation, which is implemented using `Projected*` types (basically, OGC features with a third coordinate for simplification value + bounding boxes, and additionally storing polygon area + line length for each linear ring).

To switch to a geometry.hpp-powered GeoJSON-VT-C++ in Mapbox GL Native, we need to make it possible to create GeoJSON-VT index from structures in the code directly, without the GeoJSON step. Currently this is done in hacky way by exposing `Projected*` classes from GeoJSON-VT and then reconstructing them in https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/annotation/shape_annotation_impl.cpp.

Instead we would need to either have separate `convert_geojson` and `convert_geometry` code paths, or just fully ditch GeoJSON conversion and only accept geometry.hpp for the input, moving the GeoJSON parsing responsibility to GL Native.

cc @artemp @jfirebaugh

**Comment by artemp** [comment]
@mourner - I thinks taking GeoJSON specific stuff out is a smart move, yes ^

**Comment by mourner** [comment]
Per chat, @kkaefer suggests making `mapbox/geojson.hpp` that converts from GeoJSON to geometry.hpp representation, and then switch to that in gl-native while ditching GeoJSON code from this repo. Sounds like a great plan.

**Comment by mourner** [comment]
Here's a rough bullet list of things that need to be done, per chat with @springmeyer:

- [ ] create a `mapbox/geojson.hpp` library that converts raw GeoJSON data to geometry.hpp (would be similar to [convert.cpp](https://github.com/mapbox/geojson-vt-cpp/blob/master/src/convert.cpp) code)
- [ ] ditch GeoJSON conversion code from this repo and make geometry.hpp representation the input
- [ ] hide all `Projected*` classes and `converFeatures` static method from public API
- [ ] make GeoJSONVT index creation a one-step process again (accepting geometry.hpp in constructor instead of `ProjectedFeature` vector generated by `convertFeatures`)
- [ ] switch GL Native to use `geojson.hpp` for GeoJSON parsing and switch to new geojson-vt-cpp with geometry.hpp input
- [ ] switch GL Native shape annotations implementation to use geometry.hpp representation instead of using `Projected*`
- [ ] update remaining types in `types.hpp` to use `geometry.hpp` — `Feature`, `Tags`, etc.
- [ ] if possible, update internal `Projected*` classes to reuse as much geometry.hpp as possible (relies on 3rd coord, etc.)

**Comment by kkaefer** [comment]
🎉
