### ISSUE TITLE
Protect against invalid type access in Convert::calcBBox

### ISSUE THREAD

**Issue by springmeyer** [mapbox/geojson-vt-cpp#42]
The backtraces from https://github.com/mapbox/mapbox-gl-native/issues/3926 indicate that a null feature geometry is being passed to `Convert::calcBBox`. The current code does not protect from this. We should fix this by using the visitor pattern (ideally) or at least by calling `feature.geometry.is<type>()` before calling `feature.geometry.get<type>()`.

This commit https://github.com/mapbox/geojson-vt-cpp/commit/274f715f017c1f34004c133de15e40caf677e8d9 fixed this up for addFeature, but a potential `std::runtime_error` will still be triggered at https://github.com/mapbox/geojson-vt-cpp/blob/master/src/convert.cpp#L262.

**Comment by jfirebaugh** [comment]
Interesting. How did you determine that it's a null feature?

**Comment by springmeyer** [comment]
Sorry, edited to be more clear above. It looks like a geometry type is being requested that is not inside the variant, not necessarily a null. I don't have a testcase or conclusive proof, just reading the backtrace shows that `.get<>` is failing which means the requested type does not exist.

**Comment by jfirebaugh** [comment]
I think the underlying issue is that geojson-vt-cpp wants the invariant that a `Point` feature always has a `ProjectedPoints` geometry, and a non-`Point` feature always has a `ProjectedRings` geometry. If that's the case, then a fix like #43 is hiding the underlying issue, which is that some other part of the code is violating that invariant.

**Comment by springmeyer** [comment]
@jfirebaugh thanks for the help. I'll close #43 then and we'll wait for more of a sense of the underlying problem.

**Comment by mourner** [comment]
I remember @mikemorris having a similar problem very long time ago, but we couldn't get a reproducible test case that time either.

**Comment by mikemorris** [comment]
@mourner Yea, I was trying to diagnose https://github.com/mapbox/mapbox-gl-native/issues/2926 and found the problematic line, but couldn't determine the proper fix.

**Comment by mourner** [comment]
Addressed by #45 (with visitor pattern for bbox calculation).
