### ISSUE TITLE
Possible undefined var being used like in geojson-vt

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/geojson-vt-cpp#55]
@mourner 

Could [this line in wrap](https://github.com/mapbox/geojson-vt-cpp/blob/master/include/mapbox/geojsonvt/wrap.hpp#L29) result in [this line from clip](https://github.com/mapbox/geojson-vt-cpp/blob/master/include/mapbox/geojsonvt/clip.hpp#L98) being undefined?

My cpp is really bad so I'm not sure, but quickly exiting is what was going on with the [geojson-vt](https://github.com/mapbox/geojson-vt/pull/69) bug so I thought I'd check.

**Comment by mourner** [comment]
It'll be fine because [clip returns a features vector](https://github.com/mapbox/geojson-vt-cpp/blob/master/include/mapbox/geojsonvt/clip.hpp#L213), which will be empty in case of an early return.
