### ISSUE TITLE
release with gl-native

### ISSUE THREAD

**Issue by incanus** [mapbox/geojson-vt-cpp#6]
Branched my initial import into `master` as of https://github.com/mapbox/geojson-vt-cpp/commit/a36ee820ccd9abf460f993eb1c03cf798d0748f6, then cherry-picked the non-GYP-related commits such as code style, RapidJSON headers, and getting rid of the `bool()` operator. Pushed this to [`non-gyp`](https://github.com/mapbox/geojson-vt-cpp/tree/non-gyp), which I will integrate into gl-native as a submodule until our GYP woes here are through. 

/cc @kkaefer

**Comment by incanus** [comment]
Happening in https://github.com/mapbox/mapbox-gl-native/commit/9ed12f4f65bc497ba7abcd4c50ccb56a89779b74

**Comment by incanus** [comment]
BTW my hesitation to use the post-GYP commits is because all of the source was moved into a `src` subfolder, plus many more files were added, and GYP in GL brings those into the Xcode project. Just going for the code wins in a pin right now in order to land https://github.com/mapbox/mapbox-gl-native/pull/1655.

**Comment by mourner** [comment]
Done?
