### ISSUE TITLE
undefined reference to `mapbox::geojson::parse`

### ISSUE THREAD

**Issue by aman-tiwari** [mapbox/geojson-vt-cpp#67]
When I run `make debug`, I get these errors:
```
g++  -I include -std=c++14 -Wall -Wextra -g -O0 -DDEBUG debug/debug.cpp -o build/debug `.mason/mason cflags variant 1.1.4` `.mason/mason cflags geometry 0.9.2` `.mason/mason cflags geojson 0.4.0` `.mason/mason static_libs geojson 0.4.0` `.mason/mason cflags glfw 3.1.2` `.mason/mason static_libs glfw 3.1.2` `.mason/mason ldflags glfw 3.1.2`
/tmp/ccb9EvOZ.o: In function `main::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#2}::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const':
/home/studio/aman/geojson-vt-cpp/debug/debug.cpp:95: undefined reference to `mapbox::geojson::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
Makefile:41: recipe for target 'build/debug' failed
make: *** [build/debug] Error 1
```
I've run `make mason_packages/headers/geometry` and it says it successfully installed all packages but still the error is there. What could be the cause?

Thank you for any help!

**Comment by mourner** [comment]
Not sure what might have caused this, @springmeyer any clues?

**Comment by mourner** [comment]
I think this is due to an outdated state of mason — I just encountered something similar, and when I ran `rm -rf mason_packages` and then `git submodule update --init`, it worked. Let me know if this is still an issue.

**Comment by mourner** [comment]
OK, looks like I was wrong — it works with Xcode but fails for other compilers, as seen on this Travis job: https://travis-ci.org/mapbox/geojson-vt-cpp/builds/394651629
