### ISSUE TITLE
Missing some validation checks in InternalTile::transform()

### ISSUE THREAD

**Issue by xylosper** [mapbox/geojson-vt-cpp#81]
* When simplifying a line string, the transformed line string should have 2 or more points. Otherwise, it should return an empty line string.
* When simplifying a linear ring, the transformed linear ring should have 3 or more points. Otherwise, it should return an empty linear ring.
* When simplifying a polygon, the transformed polygon should have one exterior ring at first. If exterior ring is ignored, it should return an empty polygon.

These validation checks should be considered to follow GeoJSON specifications.

**Comment by mourner** [comment]
That sounds good to me! Would you be open to submitting a pull request for these changes?

**Comment by xylosper** [comment]
I can make a pull request in a couple of days I think. Isn't it too late?
If you can't wait, please feel free to fix it by yourself. I don't care any credit of this idea.

**Comment by mourner** [comment]
There's no rush — take your time. Those fixes don't seem urgent — e.1-point lines and 2-point rings will be filtered out anyway because of length/area filtering, and if an outer ring is filtered out, the ring will be too. So implicitly those cases are already handled if I understand this correctly.
